server.port=8080
spring.application.name=saga-orchestrator
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sagadb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:payment}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
services.order.url=${ORDER_SERVICE_URL:http://localhost:8081}
services.payment.url=${PAYMENT_SERVICE_URL:http://localhost:8082}
services.inventory.url=${INVENTORY_SERVICE_URL:http://localhost:8083}

